// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBusW1fm0RXpimEl10JlvF9XHipdv-iBR0',
    appId: '1:932132170463:web:ccf8c3f5a2db28c1bb576a',
    messagingSenderId: '932132170463',
    projectId: 'booklibrary-51b91',
    authDomain: 'booklibrary-51b91.firebaseapp.com',
    storageBucket: 'booklibrary-51b91.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA30sLZHsbbeqv3iTd-WpivbF9ypDL_DGY',
    appId: '1:932132170463:android:8eb596b917f59fe3bb576a',
    messagingSenderId: '932132170463',
    projectId: 'booklibrary-51b91',
    storageBucket: 'booklibrary-51b91.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpYff3Ka9u25qvfr43cu-Ftu-aZ1Q7ZAc',
    appId: '1:932132170463:ios:4c8fc6a23e01d905bb576a',
    messagingSenderId: '932132170463',
    projectId: 'booklibrary-51b91',
    storageBucket: 'booklibrary-51b91.firebasestorage.app',
    iosBundleId: 'com.example.bookVilla',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpYff3Ka9u25qvfr43cu-Ftu-aZ1Q7ZAc',
    appId: '1:932132170463:ios:4c8fc6a23e01d905bb576a',
    messagingSenderId: '932132170463',
    projectId: 'booklibrary-51b91',
    storageBucket: 'booklibrary-51b91.firebasestorage.app',
    iosBundleId: 'com.example.bookVilla',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBusW1fm0RXpimEl10JlvF9XHipdv-iBR0',
    appId: '1:932132170463:web:7b4f00ec8d7adb5bbb576a',
    messagingSenderId: '932132170463',
    projectId: 'booklibrary-51b91',
    authDomain: 'booklibrary-51b91.firebaseapp.com',
    storageBucket: 'booklibrary-51b91.firebasestorage.app',
  );

}